function SpawnRegions()
	return {
		{ name = "Muldraugh, KY", file = "media/maps/Muldraugh, KY/spawnpoints.lua" },
		{ name = "Riverside, KY", file = "media/maps/Riverside, KY/spawnpoints.lua" },
		{ name = "Rosewood, KY", file = "media/maps/Rosewood, KY/spawnpoints.lua" },
		{ name = "West Point, KY", file = "media/maps/West Point, KY/spawnpoints.lua" },
		{ name = "AZSpawn", file = "media/maps/AZSpawn/spawnpoints.lua" },
		{ name = "ModTemplateWorld1", file = "media/maps/ModTemplateWorld1/spawnpoints.lua" },
		{ name = "ModTemplateWorld2", file = "media/maps/ModTemplateWorld2/spawnpoints.lua" },
		{ name = "constructionsitenoloot", file = "media/maps/constructionsitenoloot/spawnpoints.lua" },
		{ name = "firewatchtowernoloot", file = "media/maps/firewatchtowernoloot/spawnpoints.lua" },
		{ name = "NewEkron", file = "media/maps/NewEkron/spawnpoints.lua" },
		{ name = "Old Pine Village", file = "media/maps/Old Pine Village/spawnpoints.lua" },
		{ name = "Many Spawns Casual", file = "media/maps/Many Spawns Casual/spawnpoints.lua" },
		{ name = "Many Spawns root", file = "media/maps/Many Spawns root/spawnpoints.lua" },
		{ name = "Many Spawns All", file = "media/maps/Many Spawns All/spawnpoints.lua" },
		{ name = "quarantinecheckpointnoloot", file = "media/maps/quarantinecheckpointnoloot/spawnpoints.lua" },
		{ name = "RabbitHashKY", file = "media/maps/RabbitHashKY/spawnpoints.lua" },
		{ name = "Refordville", file = "media/maps/Refordville/spawnpoints.lua" },
		{ name = "spencermansionnoloot", file = "media/maps/spencermansionnoloot/spawnpoints.lua" },
		{ name = "Checkpoint", file = "media/maps/Checkpoint/spawnpoints.lua" },
		{ name = "FirewatchCamp", file = "media/maps/FirewatchCamp/spawnpoints.lua" },
		{ name = "KnoxHeights", file = "media/maps/KnoxHeights/spawnpoints.lua" },
		{ name = "SpencerSettlement", file = "media/maps/SpencerSettlement/spawnpoints.lua" },
		{ name = "KS10YL", file = "media/maps/KS10YL/spawnpoints.lua" },
		{ name = "10YL", file = "media/maps/10YL/spawnpoints.lua" },
		{ name = "RC10YL", file = "media/maps/RC10YL/spawnpoints.lua" },
		{ name = "SOS10YL", file = "media/maps/SOS10YL/spawnpoints.lua" },
		{ name = "Fort Knox, KY by Woldren", file = "media/maps/Fort Knox, KY by Woldren/spawnpoints.lua" },
		{ name = "Many Spawns Louisville", file = "media/maps/Many Spawns Louisville/spawnpoints.lua" },
		{ name = "Audubon", file = "media/maps/Audubon/spawnpoints.lua" },
		{ name = "Central Louisville", file = "media/maps/Central Louisville/spawnpoints.lua" },
		{ name = "Evergreen Hill", file = "media/maps/Evergreen Hill/spawnpoints.lua" },
		{ name = "Old Louisville", file = "media/maps/Old Louisville/spawnpoints.lua" },
		{ name = "Phoenix Hill", file = "media/maps/Phoenix Hill/spawnpoints.lua" },
		{ name = "Rosewood", file = "media/maps/Rosewood/spawnpoints.lua" },
		{ name = "Valley Station", file = "media/maps/Valley Station/spawnpoints.lua" },
		{ name = "West Point", file = "media/maps/West Point/spawnpoints.lua" },
		{ name = "RavenCreek", file = "media/maps/RavenCreek/spawnpoints.lua" },
	}
end
